name: Upload Python Package

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: set python version
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: download dependencies
      run: |
        pip install setuptools
        pip install twine
        pip install keyring keyrings.alt

    - name: build package
      run: python setup.py sdist

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*