name: Upload Python Package
# PyPI token available and set
on:
    release:
      types: [published]
  
permissions:
  contents: read

jobs:
  pypi-publish:

    name: upload releash to PyPI
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: set python version
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: download dependencies
      run: pip3 install setuptools --break-system-packages && pip3 install twine --break-system-packages && python3 -m pip install -U keyring keyrings.alt --break-system-packages
    - name: basic configuration
      run: python3 setup.py sdist && twine upload dist/*
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
