name: Upload Python Package
# PyPI token available and set
on:
  push:
    branches: [ "main" ]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: upload releash to PyPI
    runs-on: ubuntu-latest
    environment:
        name: pypi
        url: https://pypi.org/p/dfa-visual-demo
    permissions:
        id-token: write
    steps:
    - name: download dependencies
      run: pip3 install twine 
    - name: basic configuration
      run: python3 setup.py sdist bdist_wheel && twine upload dist/*
    - name: publish package to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
