name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    name: upload releash to PyPI
    runs-on: ubuntu-latest
    environment:
        name: pypi
        url: https://pypi.org/p/dfa-visual-demo
    permissions:
        id-token: write
    steps:
    - name: publish package to pypi
      uses: pypa/gh-action-pypi-publish@release/v1
